[tool.poetry]
name = "griptape-labs"
version = "0.1.0"
description = "Experimental tools and extensions for Griptape."
authors = ["Griptape <hello@griptape.ai>"]
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/griptape-ai/griptape-labs"

[tool.poetry.dependencies]
python = "^3.9"
griptape = "*"

[tool.poetry.group.test.dependencies]
pytest = "~=7.1"
pytest-cover = "*"
twine = ">=4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
